# bimrocket-server config

# bimrocket.location is set by default to ${user.home}/bimrocket
# but can be changed via JVM property or environ variable

# service config
services:

  # security service
  security:
    adminPassword: bimrocket
    passwordPattern: '^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=_\-\.])(?=\S+$).{8,}$'
    authorizationCacheTimeout: 300
    userCacheTimeout: 300
    roleCacheTimeout: 300
    ldap:
      enabled: false
      url: ldap://dc1.santfeliu.local
      domain: santfeliu.local
      searchBase: DC=santfeliu,DC=local
      adminUsername: admin
      adminPassword: changeit
    store:
      class: org.bimrocket.service.security.store.orient.SecurityOrientDaoStore
      orient:
        database: bimdb

  # bcf service
  bcf:
    templateProjectName: template
    store:
      class: org.bimrocket.service.bcf.store.orient.BcfOrientDaoStore
      orient:
        database: bimdb
    mail:
      createTopic:
        subject: '#{project.name}##{index}: #{title} [#{priority}]'
        body: '#{description}'

  # cloudfs service
  cloudfs:
    directory: ${bimrocket.location}/cloudfs
    folders:
      - models
      - scripts
      - reports
      - ifc_snapshots

  # ifcdb service
  ifcdb:

  # print service
  print:
    directory: ${bimrocket.location}/printsvc
    title: 'Bimrocket print'
    creator: 'Bimrocket PrintService'

  # mail service
  mail:
    enabled: false
    host: helios
    port: 25
    startTls: false
    auth: false
    username: none
    password: none
    from: 'admin@bimrocket.org'
    contentType: 'text/plain;charset=ISO-8859-1'

  # proxy service
  proxy:
    validUrls:
      - https://api.openai.com/
      - https://api.bsdd.buildingsmart.org/
    aliases:
      chatgpt:
        url: https://api.openai.com/v1/chat/completions
        ipFilter: ''
        authorization: changeit

# database config
databases:
  bimdb:
    url: embedded:${bimrocket.location}/db/bimdb
    username: root
    password: orientdb
  IFC2X3:
    url: embedded:${bimrocket.location}/db/IFC2X3
    username: root
    password: orientdb
  IFC4:
    url: embedded:${bimrocket.location}/db/IFC4
    username: root
    password: orientdb

