version: '3.8'

services:
  bimrocket-server:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: bimrocket-server
    container_name: bimrocket-server
    restart: always
    environment:
      - BIMROCKET_DATA_PATH=/root/bimrocket
      - bimrocket_services_security_oauth2_keycloak_urlAuthenticationToken=https://iam.i2cat.net/auth/realms/SEG/protocol/openid-connect/token
      - bimrocket_services_security_oauth2_keycloak_clientId=bim
      - bimrocket_services_security_oauth2_keycloak_secretId=SibGBtmT9yWfH0BwKcXx3n1sbU9lAOIL
      - bimrocket_services_security_oauth2_valid_urlAuthenticationToken=https://accounts-dev.aoc.cat/o/oauth2/token
      - bimrocket_services_security_oauth2_valid_urlGetUserInfo=https://identitats-pre.aoc.cat/serveis-rest/getUserInfo 
      - bimrocket_services_security_oauth2_valid_clientId=serveis.aoc.cat
      - bimrocket_services_security_oauth2_valid_secretId=secret_id
      - bimrocket_services_security_oauth2_gicar_urlAuthenticationToken=https://preproduccio.endpointma.autenticaciogicar4.extranet.gencat.cat/realms/gicarcpd4/protocol/openid-connect/token
      - bimrocket_services_security_oauth2_gicar_urlGetUserInfo=https://preproduccio.endpointma.autenticaciogicar4.extranet.gencat.cat/realms/gicarcpd4/protocol/openid-connect/userinfo
      - bimrocket_services_security_oauth2_gicar_clientId=client_id
      - bimrocket_services_security_oauth2_gicar_secretId=secret_id
 
    ports:
      - "9090:8080"
    volumes:
      - ../target/bimrocket-server.war:/usr/local/tomcat/webapps/bimrocket-server.war
      - ../src/main/resources/application.yaml:/root/bimrocket/bimrocket-server.yaml
    networks:
      - bimrocket_network

  orientdb:
    image: orientdb:latest
    container_name: orientdb
    restart: always
    environment:
      - ORIENTDB_ROOT_PASSWORD=orientdb
    ports:
      - "2424:2424" # Binary protocol
      - "2480:2480" # HTTP protocol
    volumes:
      - ./orientdb_data:/orientdb/databases
      - ./orientdb_backup:/orientdb/backup
    networks:
      - bimrocket_network

networks:
  bimrocket_network:
    driver: bridge
